version : '1.0'

services:
  app:
    container_name: app
    image: vlad/app:1.0
    build:
      .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
  db :
    container_name: db
    image: 'postgres:13.2-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
